---
title: "Short Bio"
author: "Padmaswari, Made Harumi"
date: "6/13/2022"
output: html_document
---
<p> Made Harumi Padmaswari is a third-year doctoral student in Cell and Molecular Biology program at the University of Arkansas, working under Dr. Christopher Nelson in Biomedical Engineering department. Before coming to the US in 2019, Harumi earned a medical degree in Indonesia and had worked in a hospital as a general physician for two years. As a physician, she realized that to cure diseases precisely and efficiently, we need to treat the source of the problem, the gene. Awarded Fulbright International Student scholarship in 2019, she determined to study CRISPR/Cas system, a new and versatile gene editing method in the biomedical research field, as a tool to edit muscle genes.
<p> Harumi’s doctoral research is focused on designing DNA integration constructs that can insert the reporter gene and therapeutic gene for muscular disease efficiently. Her research is also particularly interested in screening the site in the genome that can be safely edited and inserted without having adverse effects on the genome nearby. Currently, she is focusing her work on Duchenne Muscular Dystrophy and hemophilia, but upon completion of her study, she intends to apply her knowledge in a clinically translatable gene therapy field.